config/routes.rb
Rails.application.routes.draw do
  resources :price_alert_alarms
  resources :price_alerts
  resources :alerts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alert.rb
class Alert < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/price_alert.rb
class PriceAlert < ApplicationRecord
end

app/models/price_alert_alarm.rb
class PriceAlertAlarm < ApplicationRecord
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]

  # GET /alerts
  # GET /alerts.json
  def index
    @alerts = Alert.all
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = Alert.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
        format.json { render :show, status: :created, location: @alert }
      else
        format.html { render :new }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to @alert, notice: 'Alert was successfully updated.' }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to alerts_url, notice: 'Alert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(:name, :type, :symbol, :current_price, :cap_price, :floor_price, :expected_alert_till_date, :mobile_number, :phone_alert, :message_alert)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/price_alert_alarms_controller.rb
class PriceAlertAlarmsController < ApplicationController
  before_action :set_price_alert_alarm, only: [:show, :edit, :update, :destroy]

  # GET /price_alert_alarms
  # GET /price_alert_alarms.json
  def index
    @price_alert_alarms = PriceAlertAlarm.all
  end

  # GET /price_alert_alarms/1
  # GET /price_alert_alarms/1.json
  def show
  end

  # GET /price_alert_alarms/new
  def new
    @price_alert_alarm = PriceAlertAlarm.new
    system "echo catdoodoo>>~/test_file.txt"
  end

  # GET /price_alert_alarms/1/edit
  def edit
  end

  # POST /price_alert_alarms
  # POST /price_alert_alarms.json
  def create
    @price_alert_alarm = PriceAlertAlarm.new(price_alert_alarm_params)
    #python persecscript.py HDFCBANK 8871733514 1300 1200 3 11
    call_counter = 0
    if @price_alert_alarm.phone_alert == 1
        call_counter = 1
    end
    if @price_alert_alarm.message_alert == 1
        call_counter = 2
    end
    if @price_alert_alarm.message_alert == 1 &&  @price_alert_alarm.phone_alert ==1
        call_counter = 3
    end
    cmd_string = "python /opt/HackNight/hacknight3.0/persecurity_script.py  " + @price_alert_alarm.symbol + " " + @price_alert_alarm.mobile_number + " " + @price_alert_alarm.cap_price.round.to_s + " "+ @price_alert_alarm.floor_price.round.to_s + " "+call_counter+" " + rand(6237).to_s
    p cmd_string
    system cmd_string 
    respond_to do |format|
      if @price_alert_alarm.save
        format.html { redirect_to @price_alert_alarm, notice: 'Price alert alarm was successfully created.' }
        format.json { render :show, status: :created, location: @price_alert_alarm }
      else
        format.html { render :new }
        format.json { render json: @price_alert_alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_alert_alarms/1
  # PATCH/PUT /price_alert_alarms/1.json
  def update
    respond_to do |format|
      if @price_alert_alarm.update(price_alert_alarm_params)
        format.html { redirect_to @price_alert_alarm, notice: 'Price alert alarm was successfully updated.' }
        format.json { render :show, status: :ok, location: @price_alert_alarm }
      else
        format.html { render :edit }
        format.json { render json: @price_alert_alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_alert_alarms/1
  # DELETE /price_alert_alarms/1.json
  def destroy
    @price_alert_alarm.destroy
    respond_to do |format|
      format.html { redirect_to price_alert_alarms_url, notice: 'Price alert alarm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_alert_alarm
      @price_alert_alarm = PriceAlertAlarm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_alert_alarm_params
      params.require(:price_alert_alarm).permit(:name, :alert_type, :symbol, :current_price, :cap_price, :floor_price, :expected_alert_till_date, :mobile_number, :phone_alert, :message_alert)
    end
end

app/controllers/price_alerts_controller.rb
class PriceAlertsController < ApplicationController
  before_action :set_price_alert, only: [:show, :edit, :update, :destroy]

  # GET /price_alerts
  # GET /price_alerts.json
  def index
    @price_alerts = PriceAlert.all
  end

  # GET /price_alerts/1
  # GET /price_alerts/1.json
  def show
  end

  # GET /price_alerts/new
  def new
    @price_alert = PriceAlert.new
  end

  # GET /price_alerts/1/edit
  def edit
  end

  # POST /price_alerts
  # POST /price_alerts.json
  def create
    @price_alert = PriceAlert.new(price_alert_params)

    respond_to do |format|
      if @price_alert.save
        format.html { redirect_to @price_alert, notice: 'Price alert was successfully created.' }
        format.json { render :show, status: :created, location: @price_alert }
      else
        format.html { render :new }
        format.json { render json: @price_alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_alerts/1
  # PATCH/PUT /price_alerts/1.json
  def update
    respond_to do |format|
      if @price_alert.update(price_alert_params)
        format.html { redirect_to @price_alert, notice: 'Price alert was successfully updated.' }
        format.json { render :show, status: :ok, location: @price_alert }
      else
        format.html { render :edit }
        format.json { render json: @price_alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_alerts/1
  # DELETE /price_alerts/1.json
  def destroy
    @price_alert.destroy
    respond_to do |format|
      format.html { redirect_to price_alerts_url, notice: 'Price alert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_alert
      @price_alert = PriceAlert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_alert_params
      params.require(:price_alert).permit(:name, :type, :symbol, :current_price, :cap_price, :floor_price, :expected_alert_till_date, :mobile_number, :phone_alert, :message_alert)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/price_alert_alarms_helper.rb
module PriceAlertAlarmsHelper
end

app/helpers/price_alerts_helper.rb
module PriceAlertsHelper
end

app/views/alerts/_form.html.erb
<%= form_with(model: alert, local: true) do |form| %>
  <% if alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
        <% alert.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="field">
    <%= form.label :current_price %>
    <%= form.text_field :current_price %>
  </div>

  <div class="field">
    <%= form.label :cap_price %>
    <%= form.text_field :cap_price %>
  </div>

  <div class="field">
    <%= form.label :floor_price %>
    <%= form.text_field :floor_price %>
  </div>

  <div class="field">
    <%= form.label :expected_alert_till_date %>
    <%= form.datetime_select :expected_alert_till_date %>
  </div>

  <div class="field">
    <%= form.label :mobile_number %>
    <%= form.text_field :mobile_number %>
  </div>

  <div class="field">
    <%= form.label :phone_alert %>
    <%= form.check_box :phone_alert %>
  </div>

  <div class="field">
    <%= form.label :message_alert %>
    <%= form.check_box :message_alert %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<h1>Editing Alert</h1>

<%= render 'form', alert: @alert %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alerts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Symbol</th>
      <th>Current price</th>
      <th>Cap price</th>
      <th>Floor price</th>
      <th>Expected alert till date</th>
      <th>Mobile number</th>
      <th>Phone alert</th>
      <th>Message alert</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alerts.each do |alert| %>
      <tr>
        <td><%= alert.name %></td>
        <td><%= alert.type %></td>
        <td><%= alert.symbol %></td>
        <td><%= alert.current_price %></td>
        <td><%= alert.cap_price %></td>
        <td><%= alert.floor_price %></td>
        <td><%= alert.expected_alert_till_date %></td>
        <td><%= alert.mobile_number %></td>
        <td><%= alert.phone_alert %></td>
        <td><%= alert.message_alert %></td>
        <td><%= link_to 'Show', alert %></td>
        <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
        <td><%= link_to 'Destroy', alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alert', new_alert_path %>

app/views/alerts/new.html.erb
<h1>New Alert</h1>

<%= render 'form', alert: @alert %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @alert.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @alert.type %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @alert.symbol %>
</p>

<p>
  <strong>Current price:</strong>
  <%= @alert.current_price %>
</p>

<p>
  <strong>Cap price:</strong>
  <%= @alert.cap_price %>
</p>

<p>
  <strong>Floor price:</strong>
  <%= @alert.floor_price %>
</p>

<p>
  <strong>Expected alert till date:</strong>
  <%= @alert.expected_alert_till_date %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @alert.mobile_number %>
</p>

<p>
  <strong>Phone alert:</strong>
  <%= @alert.phone_alert %>
</p>

<p>
  <strong>Message alert:</strong>
  <%= @alert.message_alert %>
</p>

<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaAlert</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/price_alert_alarms/_form.html.erb
<%= form_with(model: price_alert_alarm, local: true) do |form| %>
  <% if price_alert_alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price_alert_alarm.errors.count, "error") %> prohibited this price_alert_alarm from being saved:</h2>

      <ul>
        <% price_alert_alarm.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :alert_type %>
    <%= form.text_field :alert_type %>
  </div>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="field">
    <%= form.label :current_price %>
    <%= form.text_field :current_price %>
  </div>

  <div class="field">
    <%= form.label :cap_price %>
    <%= form.text_field :cap_price %>
  </div>

  <div class="field">
    <%= form.label :floor_price %>
    <%= form.text_field :floor_price %>
  </div>

  <div class="field">
    <%= form.label :expected_alert_till_date %>
    <%= form.datetime_select :expected_alert_till_date %>
  </div>

  <div class="field">
    <%= form.label :mobile_number %>
    <%= form.text_field :mobile_number %>
  </div>

  <div class="field">
    <%= form.label :phone_alert %>
    <%= form.check_box :phone_alert %>
  </div>

  <div class="field">
    <%= form.label :message_alert %>
    <%= form.check_box :message_alert %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/price_alert_alarms/edit.html.erb
<h1>Editing Price Alert Alarm</h1>

<%= render 'form', price_alert_alarm: @price_alert_alarm %>

<%= link_to 'Show', @price_alert_alarm %> |
<%= link_to 'Back', price_alert_alarms_path %>

app/views/price_alert_alarms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Price Alert Alarms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Alert type</th>
      <th>Symbol</th>
      <th>Current price</th>
      <th>Cap price</th>
      <th>Floor price</th>
      <th>Expected alert till date</th>
      <th>Mobile number</th>
      <th>Phone alert</th>
      <th>Message alert</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @price_alert_alarms.each do |price_alert_alarm| %>
      <tr>
        <td><%= price_alert_alarm.name %></td>
        <td><%= price_alert_alarm.alert_type %></td>
        <td><%= price_alert_alarm.symbol %></td>
        <td><%= price_alert_alarm.current_price %></td>
        <td><%= price_alert_alarm.cap_price %></td>
        <td><%= price_alert_alarm.floor_price %></td>
        <td><%= price_alert_alarm.expected_alert_till_date %></td>
        <td><%= price_alert_alarm.mobile_number %></td>
        <td><%= price_alert_alarm.phone_alert %></td>
        <td><%= price_alert_alarm.message_alert %></td>
        <td><%= link_to 'Show', price_alert_alarm %></td>
        <td><%= link_to 'Edit', edit_price_alert_alarm_path(price_alert_alarm) %></td>
        <td><%= link_to 'Destroy', price_alert_alarm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price Alert Alarm', new_price_alert_alarm_path %>

app/views/price_alert_alarms/new.html.erb
<h1>New Price Alert Alarm</h1>

<%= render 'form', price_alert_alarm: @price_alert_alarm %>

<%= link_to 'Back', price_alert_alarms_path %>

app/views/price_alert_alarms/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<p id="notice"><%= notice %></p>
<td class=".table-striped">
<p>
  <strong>Name:</strong>
  <%= @price_alert_alarm.name %>
</p>

<p>
  <strong>Alert type:</strong>
  <%= @price_alert_alarm.alert_type %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @price_alert_alarm.symbol %>
</p>

<p>
  <strong>Current price:</strong>
  <%= @price_alert_alarm.current_price %>
</p>

<p>
  <strong>Cap price:</strong>
  <%= @price_alert_alarm.cap_price %>
</p>

<p>
  <strong>Floor price:</strong>
  <%= @price_alert_alarm.floor_price %>
</p>

<p>
  <strong>Expected alert till date:</strong>
  <%= @price_alert_alarm.expected_alert_till_date %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @price_alert_alarm.mobile_number %>
</p>

<p>
  <strong>Phone alert:</strong>
  <%= @price_alert_alarm.phone_alert %>
</p>

<p>
  <strong>Message alert:</strong>
  <%= @price_alert_alarm.message_alert %>
</p>
</td>
<%= link_to 'Edit', edit_price_alert_alarm_path(@price_alert_alarm) %> |
<%= link_to 'Back', price_alert_alarms_path %>

app/views/price_alerts/_form.html.erb
<%= form_with(model: price_alert, local: true) do |form| %>
  <% if price_alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price_alert.errors.count, "error") %> prohibited this price_alert from being saved:</h2>

      <ul>
        <% price_alert.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="field">
    <%= form.label :current_price %>
    <%= form.text_field :current_price %>
  </div>

  <div class="field">
    <%= form.label :cap_price %>
    <%= form.text_field :cap_price %>
  </div>

  <div class="field">
    <%= form.label :floor_price %>
    <%= form.text_field :floor_price %>
  </div>

  <div class="field">
    <%= form.label :expected_alert_till_date %>
    <%= form.datetime_select :expected_alert_till_date %>
  </div>

  <div class="field">
    <%= form.label :mobile_number %>
    <%= form.text_field :mobile_number %>
  </div>

  <div class="field">
    <%= form.label :phone_alert %>
    <%= form.check_box :phone_alert %>
  </div>

  <div class="field">
    <%= form.label :message_alert %>
    <%= form.check_box :message_alert %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/price_alerts/edit.html.erb
<h1>Editing Price Alert</h1>

<%= render 'form', price_alert: @price_alert %>

<%= link_to 'Show', @price_alert %> |
<%= link_to 'Back', price_alerts_path %>

app/views/price_alerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Price Alerts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Symbol</th>
      <th>Current price</th>
      <th>Cap price</th>
      <th>Floor price</th>
      <th>Expected alert till date</th>
      <th>Mobile number</th>
      <th>Phone alert</th>
      <th>Message alert</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @price_alerts.each do |price_alert| %>
      <tr>
        <td><%= price_alert.name %></td>
        <td><%= price_alert.type %></td>
        <td><%= price_alert.symbol %></td>
        <td><%= price_alert.current_price %></td>
        <td><%= price_alert.cap_price %></td>
        <td><%= price_alert.floor_price %></td>
        <td><%= price_alert.expected_alert_till_date %></td>
        <td><%= price_alert.mobile_number %></td>
        <td><%= price_alert.phone_alert %></td>
        <td><%= price_alert.message_alert %></td>
        <td><%= link_to 'Show', price_alert %></td>
        <td><%= link_to 'Edit', edit_price_alert_path(price_alert) %></td>
        <td><%= link_to 'Destroy', price_alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price Alert', new_price_alert_path %>

app/views/price_alerts/new.html.erb
<h1>New Price Alert</h1>

<%= render 'form', price_alert: @price_alert %>

<%= link_to 'Back', price_alerts_path %>

app/views/price_alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @price_alert.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @price_alert.type %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @price_alert.symbol %>
</p>

<p>
  <strong>Current price:</strong>
  <%= @price_alert.current_price %>
</p>

<p>
  <strong>Cap price:</strong>
  <%= @price_alert.cap_price %>
</p>

<p>
  <strong>Floor price:</strong>
  <%= @price_alert.floor_price %>
</p>

<p>
  <strong>Expected alert till date:</strong>
  <%= @price_alert.expected_alert_till_date %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @price_alert.mobile_number %>
</p>

<p>
  <strong>Phone alert:</strong>
  <%= @price_alert.phone_alert %>
</p>

<p>
  <strong>Message alert:</strong>
  <%= @price_alert.message_alert %>
</p>

<%= link_to 'Edit', edit_price_alert_path(@price_alert) %> |
<%= link_to 'Back', price_alerts_path %>